import {
    Activity,
    Activity as ActivityIcon,
    AlertTriangle,
    ArrowLeftRight,
    ArrowUpDown,
    BadgeCheck,
    Banknote,
    BarChart,
    BarChart2,
    BarChart3,
    Bell,
    BookOpen,
    BookUser,
    Briefcase,
    Building,
    Building2,
    Calculator,
    Calendar,
    CheckCircle,
    ClipboardList,
    Cog,
    CogIcon,
    CreditCard,
    CreditCard as CreditCardIcon,
    Currency,
    Database,
    DollarSign,
    DollarSign as DollarSignIcon,
    FileBarChart,
    FileCheck,
    FileSearch,
    FileSpreadsheet,
    FileText,
    FileText as FileTextIcon,
    Gift,
    Globe,
    HandCoins,
    HeadphonesIcon,
    History,
    Home,
    HomeIcon,
    Landmark,
    LayoutDashboard,
    Mail,
    MapPin,
    MessageSquare,
    Network,
    Package,
    PackageSearch,
    CreditCard as PaymentIcon,
    PieChart,
    PieChart as PieChartIcon,
    PiggyBank,
    Receipt,
    RefreshCw,
    Route,
    Scale,
    Search,
    Settings,
    Shield,
    Shield as ShieldIcon,
    ShoppingCart,
    Sparkles,
    TrendingDown,
    TrendingUp,
    Truck,
    User,
    UserCheck,
    UserCheck as UserCheckIcon,
    UserCog,
    UserCog as UserCogIcon,
    UserPlus,
    UserPlus as UserPlusIcon,
    Users,
    Users2,
    Users as UsersIcon,
    Wallet,
    Warehouse,
    Wrench,
} from "lucide-react"
import { PermissionAction, PermissionResource, UserRole } from "@/types/auth"

import type { LucideIcon } from "lucide-react"

export interface MenuItem {
    id: string
    label: string
    icon?: LucideIcon
    path: string
    resource: PermissionResource
    action: PermissionAction
    children?: MenuItem[]
    // Roles that can access this menu item
    allowedRoles?: UserRole[]
}

// Role-based permissions configuration
export const ROLE_PERMISSIONS: Record<UserRole, Array<{ resource: PermissionResource; actions: PermissionAction[] }>> = {
    superadmin: [
        { resource: "dashboard", actions: ["view"] },
        { resource: "financials", actions: ["view", "create", "edit", "delete"] },
        { resource: "chart-of-accounts", actions: ["view", "create", "edit", "delete"] },
        { resource: "general-ledger", actions: ["view", "create", "edit", "delete"] },
        { resource: "accounts-receivable", actions: ["view", "create", "edit", "delete"] },
        { resource: "accounts-payable", actions: ["view", "create", "edit", "delete"] },
        { resource: "payments", actions: ["view", "create", "edit", "delete"] },
        { resource: "financial-reports", actions: ["view", "create", "edit", "delete"] },
        { resource: "shipment-management", actions: ["view", "create", "edit", "delete"] },
        { resource: "shipments", actions: ["view", "create", "edit", "delete"] },
        { resource: "invoices", actions: ["view", "create", "edit", "delete"] },
        { resource: "user-management", actions: ["view", "create", "edit", "delete"] },
        { resource: "customers", actions: ["view", "create", "edit", "delete"] },
        { resource: "staff-management", actions: ["view", "create", "edit", "delete"] },
        { resource: "staff-roles", actions: ["view", "create", "edit", "delete"] },
        { resource: "warehouse-management", actions: ["view", "create", "edit", "delete"] },
        { resource: "warehouses", actions: ["view", "create", "edit", "delete"] },
        { resource: "warehouse-types", actions: ["view", "create", "edit", "delete"] },
        { resource: "courier-management", actions: ["view", "create", "edit", "delete"] },
        { resource: "vehicle-types", actions: ["view", "create", "edit", "delete"] },
        { resource: "vehicles", actions: ["view", "create", "edit", "delete"] },
        { resource: "drivers", actions: ["view", "create", "edit", "delete"] },
        { resource: "quick-quotes", actions: ["view", "create", "edit", "delete"] },
        { resource: "shipment-tracking", actions: ["view"] },
        { resource: "activities", actions: ["view"] },
        { resource: "backups", actions: ["view", "create", "delete"] },
        { resource: "settings", actions: ["view", "create", "edit", "delete"] },
        { resource: "shipping-settings", actions: ["view", "create", "edit", "delete"] },
        { resource: "inside-city", actions: ["view", "create", "edit", "delete"] },
        { resource: "outside-city", actions: ["view", "create", "edit", "delete"] },
        { resource: "costings", actions: ["view", "create", "edit", "delete"] },
        { resource: "packages", actions: ["view", "create", "edit", "delete"] },
        { resource: "sms-settings", actions: ["view", "create", "edit", "delete"] },
        { resource: "geo-settings", actions: ["view", "create", "edit", "delete"] },
        { resource: "notifications", actions: ["view", "create", "edit", "delete"] },
        { resource: "email-settings", actions: ["view", "create", "edit", "delete"] },
        { resource: "payment-settings", actions: ["view", "create", "edit", "delete"] },
        { resource: "currencies", actions: ["view", "create", "edit", "delete"] },
    ],
    admin: [
        { resource: "dashboard", actions: ["view"] },
        { resource: "financials", actions: ["view", "create", "edit"] },
        { resource: "chart-of-accounts", actions: ["view", "create", "edit"] },
        { resource: "general-ledger", actions: ["view", "create", "edit"] },
        { resource: "accounts-receivable", actions: ["view", "create", "edit"] },
        { resource: "accounts-payable", actions: ["view", "create", "edit"] },
        { resource: "payments", actions: ["view", "create", "edit"] },
        { resource: "financial-reports", actions: ["view"] },
        { resource: "shipment-management", actions: ["view", "create", "edit"] },
        { resource: "shipments", actions: ["view", "create", "edit"] },
        { resource: "invoices", actions: ["view", "create", "edit"] },
        { resource: "user-management", actions: ["view"] },
        { resource: "all-users", actions: ["view"] },
        { resource: "staff-management", actions: ["view"] },
        { resource: "staff-roles", actions: ["view"] },
        { resource: "warehouse-management", actions: ["view", "create", "edit"] },
        { resource: "warehouses", actions: ["view", "create", "edit"] },
        { resource: "warehouse-types", actions: ["view", "create", "edit"] },
        { resource: "courier-management", actions: ["view", "create", "edit"] },
        { resource: "vehicle-types", actions: ["view", "create", "edit"] },
        { resource: "vehicles", actions: ["view", "create", "edit"] },
        { resource: "drivers", actions: ["view", "create", "edit"] },
        { resource: "quick-quotes", actions: ["view", "create"] },
        { resource: "shipment-tracking", actions: ["view"] },
        { resource: "activities", actions: ["view"] },
        { resource: "backups", actions: ["view", "create", "delete"] },
        { resource: "settings", actions: ["view"] },
        { resource: "shipping-settings", actions: ["view", "create", "edit"] },
        { resource: "inside-city", actions: ["view", "create", "edit"] },
        { resource: "outside-city", actions: ["view", "create", "edit"] },
        { resource: "costings", actions: ["view", "create", "edit"] },
        { resource: "packages", actions: ["view", "create", "edit"] },
        { resource: "sms-settings", actions: ["view", "create", "edit"] },
        { resource: "geo-settings", actions: ["view"] },
        { resource: "notifications", actions: ["view", "create", "edit"] },
        { resource: "email-settings", actions: ["view", "create", "edit"] },
        { resource: "payment-settings", actions: ["view", "create", "edit"] },
        { resource: "currencies", actions: ["view"] },
    ],
    manager: [
        { resource: "dashboard", actions: ["view"] },
        { resource: "financials", actions: ["view"] },
        { resource: "chart-of-accounts", actions: ["view"] },
        { resource: "general-ledger", actions: ["view"] },
        { resource: "accounts-receivable", actions: ["view"] },
        { resource: "accounts-payable", actions: ["view"] },
        { resource: "payments", actions: ["view"] },
        { resource: "financial-reports", actions: ["view"] },
        { resource: "shipment-management", actions: ["view", "create", "edit"] },
        { resource: "shipments", actions: ["view", "create", "edit"] },
        { resource: "invoices", actions: ["view", "create", "edit"] },
        { resource: "user-management", actions: ["view"] },
        { resource: "all-users", actions: ["view"] },
        { resource: "staff-management", actions: ["view"] },
        { resource: "staff-roles", actions: ["view"] },
        { resource: "warehouse-management", actions: ["view"] },
        { resource: "warehouses", actions: ["view"] },
        { resource: "warehouse-types", actions: ["view"] },
        { resource: "courier-management", actions: ["view"] },
        { resource: "vehicle-types", actions: ["view"] },
        { resource: "vehicles", actions: ["view"] },
        { resource: "drivers", actions: ["view"] },
        { resource: "quick-quotes", actions: ["view", "create"] },
        { resource: "shipment-tracking", actions: ["view"] },
        { resource: "settings", actions: ["view"] },
    ],
    agent: [
        { resource: "dashboard", actions: ["view"] },
        { resource: "shipment-management", actions: ["view"] },
        { resource: "shipments", actions: ["view", "create"] },
        { resource: "financials", actions: ["view"] },
        { resource: "payments", actions: ["view"] },
        { resource: "quick-quotes", actions: ["view", "create"] },
        { resource: "shipment-tracking", actions: ["view"] },
    ],
    driver: [
        { resource: "dashboard", actions: ["view"] },
        { resource: "shipment-management", actions: ["view"] },
        { resource: "shipment-tracking", actions: ["view"] },
        { resource: "shipments", actions: ["view", "edit"] },
    ],
    customer: [
        { resource: "dashboard", actions: ["view"] },
        { resource: "customer-shipments", actions: ["view", "create"] },
        { resource: "shipment-tracking", actions: ["view"] },
    ],
}

export const mainMenu: MenuItem[] = [
    {
        id: "dashboard",
        label: "Dashboard",
        icon: LayoutDashboard,
        path: "/dashboard",
        resource: "dashboard",
        action: "view",
    },
    {
        id: "shipment-management",
        label: "Shipment Management",
        icon: Package,
        path: "/shipment-management",
        resource: "shipment-management",
        action: "view",
        children: [
            {
                id: "shipments",
                label: "All Shipments",
                icon: PackageSearch,
                path: "/shipment-management/shipments",
                resource: "shipments",
                action: "view",
            },
            {
                id: "shipments-create",
                label: "Create",
                icon: UserPlus,
                path: "/shipment-management/shipments/create",
                resource: "shipments",
                action: "create",
            },
        ],
    },
    {
        id: "financials",
        label: "Financials",
        icon: DollarSign,
        path: "/financials",
        resource: "financials",
        action: "view",
        children: [
            {
                id: "chart-of-accounts",
                label: "Chart of Accounts",
                icon: FileBarChart,
                path: "/financials/chart-of-accounts",
                resource: "chart-of-accounts",
                action: "view",
            },
            {
                id: "general-ledger",
                label: "General Ledger",
                icon: BookOpen,
                path: "/financials/ledger",
                resource: "general-ledger",
                action: "view",
            },
            {
                id: "accounts-receivable",
                label: "Invoices (Receivables)",
                icon: TrendingUp,
                path: "/financials/receivables",
                resource: "accounts-receivable",
                action: "view",
            },
            {
                id: "accounts-payable",
                label: "Bills (Payables)",
                icon: TrendingDown,
                path: "/financials/payables",
                resource: "accounts-payable",
                action: "view",
            },
            {
                id: "payments",
                label: "Payments",
                icon: CreditCard,
                path: "/financials/payments",
                resource: "payments",
                action: "view",
            },
            {
                id: "financial-reports",
                label: "Financial Reports",
                icon: FileText,
                path: "/financials/reports",
                resource: "financial-reports",
                action: "view",
            },
        ],
    },
    {
        id: "invoices",
        label: "Invoices",
        icon: Receipt,
        path: "/invoices",
        resource: "invoices",
        action: "view",
    },
    {
        id: "user-management",
        label: "User Management",
        icon: Users,
        path: "/user-management",
        resource: "user-management",
        action: "view",
        children: [
            {
                id: "customers",
                label: "Customers",
                icon: Users2,
                path: "/user-management/customers",
                resource: "customers",
                action: "view",
            },
            {
                id: "staff-management",
                label: "Staff Management",
                icon: UserCog,
                path: "/user-management/staff-management",
                resource: "staff-management",
                action: "view",
            },
            {
                id: "staff-roles",
                label: "Staff Roles",
                icon: BadgeCheck,
                path: "/user-management/staff-roles",
                resource: "staff-roles",
                action: "view",
            },
        ],
    },
    {
        id: "warehouse-management",
        label: "Warehouse Management",
        icon: Warehouse,
        path: "/warehouse-management",
        resource: "warehouse-management",
        action: "view",
        children: [
            {
                id: "warehouses",
                label: "Warehouses",
                icon: Building2,
                path: "/warehouse-management/warehouses",
                resource: "warehouses",
                action: "view",
            },
            {
                id: "warehouse-types",
                label: "Warehouse Types",
                icon: Building,
                path: "/warehouse-management/warehouse-types",
                resource: "warehouse-types",
                action: "view",
            },
        ],
    },
    {
        id: "courier-management",
        label: "Courier Management",
        icon: Truck,
        path: "/courier-management",
        resource: "courier-management",
        action: "view",
        children: [
            {
                id: "vehicle-types",
                label: "Vehicle Types",
                icon: Truck,
                path: "/courier-management/vehicle-types",
                resource: "vehicle-types",
                action: "view",
                children: [
                    {
                        id: "vehicle-types",
                        label: "All Vehicle Types",
                        icon: Truck,
                        path: "/courier-management/vehicle-types",
                        resource: "vehicle-types",
                        action: "view",
                    },
                    {
                        id: "vehicle-types-create",
                        label: "Create",
                        icon: UserPlus,
                        path: "/courier-management/vehicle-types/create",
                        resource: "vehicle-types",
                        action: "create",
                    },
                ],
            },
            {
                id: "vehicles",
                label: "Vehicles",
                icon: Truck,
                path: "/courier-management/vehicles",
                resource: "vehicles",
                action: "view",
                children: [
                    {
                        id: "vehicles",
                        label: "All Vehicles",
                        icon: Truck,
                        path: "/courier-management/vehicles",
                        resource: "vehicles",
                        action: "view",
                    },
                    {
                        id: "vehicles-create",
                        label: "Create",
                        icon: UserPlus,
                        path: "/courier-management/vehicles/create",
                        resource: "vehicles",
                        action: "create",
                    },
                ],
            },
            {
                id: "drivers",
                label: "Drivers",
                icon: User,
                path: "/courier-management/drivers",
                resource: "drivers",
                action: "view",
                children: [
                    {
                        id: "drivers",
                        label: "All Drivers",
                        icon: User,
                        path: "/courier-management/drivers",
                        resource: "drivers",
                        action: "view",
                    },
                    {
                        id: "drivers-create",
                        label: "Create",
                        icon: UserPlus,
                        path: "/courier-management/drivers/create",
                        resource: "drivers",
                        action: "create",
                    },
                ],
            },
        ],
    },
    {
        id: "quick-quotes",
        label: "Quick Quotes",
        icon: FileSearch,
        path: "/quick-quotes",
        resource: "quick-quotes",
        action: "view",
    },
    {
        id: "shipment-tracking",
        label: "Shipment Tracking",
        icon: Search,
        path: "/shipment-tracking",
        resource: "shipment-tracking",
        action: "view",
    },
    {
        id: "activities",
        label: "Activities",
        icon: Activity,
        path: "/activities",
        resource: "activities",
        action: "view",
        allowedRoles: ["superadmin", "admin"],
    },
    {
        id: "customer-shipments",
        label: "Create Shipment",
        icon: Package,
        path: "/shipments/customer/create",
        resource: "customer-shipments",
        action: "create",
        allowedRoles: ["customer"],
    },
]

export const secondaryMenu: MenuItem[] = [
    {
        id: "settings",
        label: "General Settings",
        icon: Settings,
        path: "/settings",
        resource: "settings",
        action: "view",
        children: [
            {
                id: "settings-general",
                label: "Settings",
                icon: Cog,
                path: "/settings/general",
                resource: "settings",
                action: "view",
            },
            {
                id: "database-mode",
                label: "Database Mode",
                icon: Database,
                path: "/settings/database-mode",
                resource: "settings",
                action: "view",
            },
            {
                id: "backups",
                label: "Backups",
                icon: Database,
                path: "/backups",
                resource: "backups",
                action: "view",
                allowedRoles: ["superadmin", "admin"],
            },
            {
                id: "shipping-settings",
                label: "Shipping",
                icon: PackageSearch,
                path: "/settings/shipping-settings",
                resource: "shipping-settings",
                action: "view",
                children: [
                    {
                        id: "inside-city",
                        label: "Inside City",
                        icon: MapPin,
                        path: "/settings/shipping-settings/inside-city",
                        resource: "inside-city",
                        action: "view",
                    },
                    {
                        id: "outside-city",
                        label: "Outside City",
                        icon: Globe,
                        path: "/settings/shipping-settings/outside-city",
                        resource: "outside-city",
                        action: "view",
                    },
                    {
                        id: "weight-based-pricing",
                        label: "Weight-Based Pricing",
                        icon: Scale,
                        path: "/settings/weight-based-pricing",
                        resource: "shipping-settings",
                        action: "view",
                    },
                ],
            },
            {
                id: "costings",
                label: "Costings",
                icon: Calculator,
                path: "/settings/costings",
                resource: "costings",
                action: "view",
            },
            {
                id: "packages",
                label: "Packages",
                icon: Package,
                path: "/settings/packages",
                resource: "packages",
                action: "view",
            },
            {
                id: "sms-settings",
                label: "SMS Settings",
                icon: MessageSquare,
                path: "/settings/sms-settings",
                resource: "sms-settings",
                action: "view",
            },
            {
                id: "geo-settings",
                label: "Geo Settings",
                icon: MapPin,
                path: "/settings/geo-settings",
                resource: "geo-settings",
                action: "view",
            },
            {
                id: "notifications",
                label: "Notifications",
                icon: Bell,
                path: "/settings/notifications",
                resource: "notifications",
                action: "view",
                allowedRoles: ["superadmin", "admin"],
            },
            {
                id: "email-settings",
                label: "Email Settings",
                icon: Mail,
                path: "/settings/email-settings",
                resource: "email-settings",
                action: "view",
            },
            {
                id: "payment-settings",
                label: "Payment Settings",
                icon: PaymentIcon,
                path: "/settings/payments",
                resource: "payment-settings",
                action: "view",
            },
            {
                id: "currencies",
                label: "Currencies",
                icon: Currency,
                path: "/settings/currencies",
                resource: "currencies",
                action: "view",
            },
        ],
    },
]
