export const MENU_LIST = {
  // Main Menu
  dashboard: 'dashboard',
  financials: 'financials',
  chartofaccounts: 'chart-of-accounts',
  generalledger: 'general-ledger',
  accountsreceivable: 'accounts-receivable',
  accountspayable: 'accounts-payable',
  payments: 'payments',
  financialreports: 'financial-reports',
  shipmentmanagement: 'shipment-management',
  shipments: 'shipments',
  invoices: 'invoices',
  usermanagement: 'user-management',
  customers: 'customers',
  staffmanagement: 'staff-management',
  staffroles: 'staff-roles',
  warehousemanagement: 'warehouse-management',
  warehouses: 'warehouses',
  warehousetypes: 'warehouse-types',
  couriermanagement: 'courier-management',
  vehicletypes: 'vehicle-types',
  vehicles: 'vehicles',
  drivers: 'drivers',
  quickquotes: 'quick-quotes',
  shipmenttracking: 'shipment-tracking',
  activities: 'activities',
  backups: 'backups',
  
  // Secondary Menu (Settings)
  settings: 'settings',
  shippingsettings: 'shipping-settings',
  insidecity: 'inside-city',
  outsidecity: 'outside-city',
  costings: 'costings',
  packages: 'packages',
  smssettings: 'sms-settings',
  geosettings: 'geo-settings',
  notifications: 'notifications',
  emailsettings: 'email-settings',
  paymentsettings: 'payment-settings',
  currencies: 'currencies',
}